name: Build and run tests (CI)

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - reopened

jobs:
  build:
    name: CI
    runs-on: [ubuntu-latest]
#    runs-on: [self-hosted, ubuntu-latest]
    env:
      GRADLE_OPTS: '-Dfile.encoding=utf-8 -Dorg.gradle.daemon=false'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test with Gradle
        run: ./gradlew clean check

